### ISSUE TITLE
Token Count?

### ISSUE THREAD

**Issue by jwax33** [Sidem/sd-ui-plugins#1]
A feature request: Add a token count so we can tell if we're over the SD limit of 75 or not when crafting spells/prompts.
I've been using this: https://beta.openai.com/tokenizer to keep an eye on it but an in-window count would be awesome.

**Comment by jwax33** [comment]
This pull request from the Automatic1111 fork might be helpful.  Kind of details their work with the tokenizer.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/1194

**Comment by Sidem** [comment]
Looks like its using a separate library https://github.com/latitudegames/GPT-3-Encoder
it's possible to extract the necessary code and implement it in the plugin, but it looks like that would bloat the size of the plugin by at least 1mb. not sure if there isnt a more elegant way to do this.. I definitely see the added value in a token counter, the rule of thumb (~4 chars = 1 token) seems like a good approximation, using that would make the count less accurate though..

After using https://beta.openai.com/tokenizer with a few examples it seems like the plugins heavy usage of (), [] and commas brings the rule of thumb down to ~2.9chars per token, so i'd probably use that instead. I'd write that simple implementation and compare the estimates with the true computed token counts and if somebody can provide an actual implementation i'd be happy to accept the pull request.

**Comment by jwax33** [comment]
Thanks for looking into it.  I will keep my eyes open for a more elegant solution.

**Comment by Sidem** [comment]
this token counter simply counts 1 token for 3 characters, should be a good rough approximate for now, when closer to 75 it's probably wise to double check with https://beta.openai.com/tokenizer till we have a built in solution

**Comment by Sidem** [comment]
After a few tests, it turns out it's really not very accurate, can you link to the documentation referencing the 75 token limit?

**Comment by jwax33** [comment]
I have not yet found a primary source for the token limit.  Pretty much everything is secondary.  The HuggingFace model card for Stable Diffusion says it uses the CLiP ViT-L/14 tokenizer.  The project page for that is located here but I didn't find a reference to token limits there:

https://github.com/openai/CLIP

Here's this from the NovelAI blog:

"The original Stable Diffusion model has a maximum prompt length of 75 CLIP tokens, plus a start and end token (77 total). This is due to the fact, that CLIP itself has this limitation and is used for providing the vector used in classifier-free guidance."
https://blog.novelai.net/novelai-improvements-on-stable-diffusion-e10d38db82ac

Subsequent Reddit posts suggest that the 77 was reduced to 75 total in an update of SD but I can't verify this.
NovelAI claims to have increased the token limit to 200+ in their version.

**Comment by Sidem** [comment]
oh interesting, so different models have different limits too, probably makes sense to not color indicate it when the token count surpasses 75 then. Not entirely sure if the CLIP tokens are the same as the GPT tokens. So this is probably inaccurate or meaningless
